services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./backend/config/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
