services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - dwengo_postgres_data:/var/lib/postgresql/data
            - ./backend/config/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    logging:
        image: grafana/loki:latest
        ports:
            - '3102:3102'
            - '9095:9095'
        volumes:
            - ./config/loki/config.yml:/etc/loki/config.yaml
            - dwengo_loki_data:/loki
        command: -config.file=/etc/loki/config.yaml
        restart: unless-stopped

    dashboards:
        image: grafana/grafana:latest
        ports:
            - '3100:3000'
        volumes:
            - dwengo_grafana_data:/var/lib/grafana
        restart: unless-stopped

volumes:
    dwengo_postgres_data:
    dwengo_loki_data:
    dwengo_grafana_data:
