services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        network_mode: 'host'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backend/config/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
